seed: 0
device: "cuda"  # cpu or cuda

input:
  training_path: datasets
  test_path: datasets
  path: datasets
  batch_size: 100
  dataset: "mnist" # "mnist" or "cifar10"


model:
  name: "ffclassifier"
  peer_normalization: 0.03
  momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.
  hidden_dim: 2000
  num_layers: 4


training:
  epochs: 100
  learning_rate: 1e-3
  weight_decay: 3e-4
  momentum: 0.9
  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3
  val_idx: 1  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: True  # Set to true to evaluate performance on test-set.


hydra:
  run:
    dir: logs